#Gathers domains that gene site has membership in

#mm10_domains.csv generated by modification of Genome liftover of mm9_domains from domain paper in domain_id_assignment.py
#gene_intergenic_#.csv generated by UNKONWN

#Exports gene_#_with_domain.csv

import pandas as pd 
import matplotlib.pyplot as plt
import csv

printed = False
def duplicates(list, item):
    """Returns index locations of item in list"""
    return [i for i, x in enumerate(list) if x == item]

chromosomes = []
start = []
end = []
id = []
chromosome_locations = {}

gene_data = []
gene_chromosomes = []
gene_start = []
gene_end = []
#load gene data
#TODO: Find where this is before rerunning
csv_file = "data/mm10_data/full_genes/full_genes.csv"
gene_data_df = pd.read_csv(csv_file, header=None, index_col=False)
for row in gene_data_df[1]:
    gene_chromosomes.append(row)
for row in gene_data_df[2]:
    gene_start.append(row)
for row in gene_data_df[3]:
    gene_end.append(row)
for x in range(len(gene_chromosomes)):
    gene_data.append([gene_chromosomes[x], gene_start[x], gene_end[x], str(gene_chromosomes[x]) + ":" + str(gene_start[x]) + "-" + str(gene_end[x])])
print("gene data loaded")

files = ['1','2','4','8']
for file in files:
    print(file + " cell started")
    #TODO: Load domain data by line, split by comma, extra the first element
    #TODO: Generate domain list by extracting features from aforementioned first element
    #TODO: Count how many genes are in TAD and format as DHS: number of genes
    #Iterate through chromosomes
    for chrom in uq_chrom:
        chrom_domains = []
        chrom_genes = []
        #populate the domains for this chromosome
        for domain_data in domain_groups:
            if domain_data[0] == chrom:
                chrom_domains.append(domain_data)
        #populate the gene sites for this chromosome
        for gene_data in gene_data:
            if gene_data[0] == chrom:
                chrom_genes.append(gene_data)
        #For each domain, assign it to the gene site if the gene site is within the domain bounds
        for domain in chrom_domains:
            gene_in_domain = []
            local_domain_list = [domain[3]]
            for gene in chrom_genes:
                if int(domain[1]) < int(gene[1]) and int(gene[2]) < int(domain[2]):
                    gene_in_domain.append(gene[3])
            local_domain_list.extend(gene_in_domain)
            if len(gene_in_domain) > 0:
                domains.append(local_domain_list)
    print("genes grouped")
    #Export data
    domain_annotated_df = pd.DataFrame(domains)
    path = "data/mm10_data/domains/domains_with_genes_" + file + ".csv"
    domain_annotated_df.to_csv(path, index=False, header=False)
    print("Data exported for " + file + " cell")


