#Splices exons from genes together to construct a region approximating a gene
#Tracks process time

#pc_gene_eo.csv generated by awk filtering of mouse gene annoatation for protein_coding, exon_number, chr, with # lines removed
#pc_ids_eo.csv generated by awk filtering of mouse gene annoatation for protein_coding, exon_number, chr, with # lines removed for column $9
#uq_pc_ids_eo.csv generated by awk filtering of pc_ids_eo.csv for unique lines

#Exports constructed_genes.csv

import time
import pandas as pd 

def duplicates(list, item):
    """Returns index locations of item in list"""
    return [i for i, x in enumerate(list) if x == item]

panda_import_time = time.process_time()
print("pandas imported in " + str(panda_import_time))

#load gene data
gene_data_df = pd.read_csv("data/mm10_data/pc_genes_eo.csv", header=None, index_col=False)
gene_data_load_time = time.process_time() - panda_import_time
print("gene data loaded in " + str(gene_data_load_time))

#pc_ids_eo doesn't have constant row size, so pandas cannot be used to load dataframe
printed = False
ids = []
path = "data/mm10_data/pc_ids_eo.csv"
with open(path) as gene_ids:
        ids_load_time = time.process_time() - gene_data_load_time
        print("gene ids loaded in " + str(ids_load_time))
        #split file into lines
        lis = [line.split() for line in gene_ids] 
        for line in lis:
            for id in line:
                #split by comma, retain gene ids
                id_values = id.split(',')
                for value in id_values:
                    if 'gene_id' in value:
                        ids.append(value)
id_processed_time = time.process_time() - ids_load_time
print('ids processed in ' + str(id_processed_time))

#load unique ids -- This is faster than searching list of seen ids
uq_ids = []
path = "data/mm10_data/uq_pc_ids_eo.csv"
uq_pc_ids_eo_df = pd.read_csv(path, header=None, index_col=False)
uq_id_load_time = time.process_time() - id_processed_time
print('unique ids loaded in ' + str(uq_id_load_time))
for row in uq_pc_ids_eo_df[0]:
    uq_ids.append(row)

chr = []
start = []
end = []

exons = []

for row in gene_data_df[0]:
    chr.append(row)
for row in gene_data_df[1]:
    start.append(row)
for row in gene_data_df[2]:
    end.append(row)

basic_exon_processed_time = time.process_time() - id_processed_time
print('basic exons processed into feature lists in ' + str(basic_exon_processed_time))
for x in range(len(chr)):
    exons.append([chr[x], start[x], end[x]])

basic_data_processed_time = time.process_time() - basic_exon_processed_time
print('basic exon data processed into gene lists ' + str(basic_exon_processed_time))


exons_in_gene = {}
#iterate through unique ids
for id in uq_ids:
    exons_for_id = []
    #find where ids and accompanying data are located by index
    indexes = duplicates(ids, id)
    for index in indexes:
        exons_for_id.append(exons[index])
        if printed == False:
            print("Value added to genes_for_id list")
            print(exons[index])
            printed = True
    exons_in_gene[id] = exons_for_id

exon_collection_time = time.process_time() - basic_data_processed_time
print("exons collected by id in " + str(exon_collection_time))
print("Number of exons: " + str(len(exons_in_gene)))
printed = False
total = 0
constructed_genes = []
#Iterate through gene ids, construct gene from left most exon and right most exon
for gene_id in exons_in_gene.keys():
    total_exon_length = 0
    #list of exon features
    exon_starts = []
    exon_ends = []
    #constructed gene values
    exon_start = 0
    exon_end = 0
    total += len(exons_in_gene[gene_id])
    for exon in exons_in_gene[gene_id]:
        total_exon_length += (int(exon[2]) - int(exon[1]))
        exon_starts.append(exon[1])
        exon_ends.append(exon[2])
    #leftmost feature
    exon_start = min(exon_starts)
    #rightmost feature
    exon_end = max(exon_ends)
    constructed_genes.append([gene_id, exon[0], exon_start, exon_end, total_exon_length])
    
avg = total / len(exons_in_gene.keys())
print("Average number of exons per gene: " + str(avg))
constructed_genes_df = pd.DataFrame(constructed_genes)
path = "data/mm10_data/constructed_genes.csv"
constructed_genes_df.to_csv(path, index=False, header=False)
