#Updates liftover file's conversion with the IDs of the TADs

#mm10_TADs.csv initially generated by liftover conversion of modified mm9_TADs file

#Exports updated mm10_TADs.csv

import pandas as pd

#load tad data
TAD_data = pd.read_csv("data/mm10_data/mm10_TADs.csv", header=None, index_col=False)

chr = []
start = []
end = []

TAD_id = []

TADs = []
for row in TAD_data[0]:
    chr.append(row)
for row in TAD_data[1]:
    start.append(row)
for row in TAD_data[2]:
    end.append(row)

#generate ids
for x in range(len(chr)):
    TAD_id.append(str(chr[x] + ":" + str(start[x]) + "-" + str(end[x])))

#generate list of tad data lists for dataframe
for x in range(len(chr)):
    TADs.append([chr[x], start[x], end[x], TAD_id[x]])

#export data
TADs_df = pd.DataFrame(TADs)
TADs_df.to_csv("data/mm10_data/mm10_TADs.csv", index=False, header=False)